### ISSUE TITLE
How / when is `/auth/code/request/` intended to be used?

### ISSUE THREAD

**Issue by SirWumpus** [merixstudio/django-trench#106]
Tried to use `/auth/code/request/` for login.  It is a protected route and needs to know the logged in user, so no good for resending login code.

Tried it for resending the activation code and it fails with `{"detail":"Not found."}`, because I think its trying to find the method that is not yet activated.

I'm confused by `/auth/code/request/`, because it doesn't appear to work for what I assumed was it purpose.

**Comment by Frikster** [comment]
I am likewise confused. I am trying to add MFA to a user using '/yubi/activate/` and it also cannot identify that the user is authenticated:

![image](https://user-images.githubusercontent.com/10172142/139941451-cb22604b-894d-4877-b4a1-bbfdcc65d31c.png)


If I however go to `/admin` I can see the test user _is_ authenticated:

![image](https://user-images.githubusercontent.com/10172142/139941356-407a9832-0f25-4186-9341-6a1f623ad2d4.png)

**Comment by wmaciejewskimer** [comment]
@SirWumpus To resend the activation code use again activation Url: https://django-trench.readthedocs.io/en/latest/endpoints.html#mfa-method-activation 
Endpoint to send the code: https://django-trench.readthedocs.io/en/latest/endpoints.html#send-the-code is used for the deactivation method or to generate new backup codes

**Comment by wmaciejewskimer** [comment]
Closing since lack of response for 4 months.

**Comment by SirWumpus** [comment]
Given that when I posted the issue I needed an answer, 12+ months later get some reply.  Business moved on, canned / boxed project. So ya. Close it. Code not viable.
