### ISSUE TITLE
Table testapp_user has no column named yubikey_id 

### ISSUE THREAD

**Issue by Frikster** [merixstudio/django-trench#119]
**Describe the bug**
When you try to create a superuser in the example demo app you get `django.db.utils.OperationalError: table testapp_user has no column named yubikey_id`

**To Reproduce**
1. Go to the [Sample App documentation](https://django-trench.readthedocs.io/en/latest/examples.html#examples)
2. Make sure after cloning that you are on the demo branch and follow all the instructions up to before `make build`
3. `make build` will fail (separate issue) due to a missing `djoser` version. Change it in `common.txt` from `djoser==1.2.1` to `djoser==1.2.2`
4. Continue the rest of the instructions. `make create_admin` will display the error message.

**Expected behavior**
An admin is created and you can log into the admin

**Screenshots**
![image](https://user-images.githubusercontent.com/10172142/139636969-b8e65c1f-fe7d-4f15-b947-58ce45a767ae.png)

**Desktop:**
 - OS: PopOS 20.04
 - Browser: Brave
 - Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)

**Additional context**
I just want to see how the "out-the-box" Yubico support works. I can use the `develop` branch to create an admin and then log in. But then I cannot seem to figure out where you add the yubikey U2F and how to map that to the public API. So I am trying the demo, but then I ran into this issue. So instructions on how to add Yubico U2F support to my django rest framework authentication is what I ultimately am looking for. Thank you.

**Comment by wmaciejewskimer** [comment]
@Frikster Does this issue still occur? Now yubikey_id is stored in MFAMethod.secret.

**Comment by wmaciejewskimer** [comment]
Closing since lack of response for 4 months.
