### ISSUE TITLE
KeyError prevents Yubico MFA activate for a user

### ISSUE THREAD

**Issue by Frikster** [merixstudio/django-trench#120]
**Describe the bug**
A KeyError prevents Yubico MFA activation at endpoint `auth/yubi/activate/`

**To Reproduce**
1. Follow [installation instructions](https://django-trench.readthedocs.io/en/latest/installation.html) and set up with `djangorestframework-simplejwt` authentication (i.e. `/auth/login/` endpoint)
2. Ensure you can authenticate a user at the `/auth/login/` endpoint to retrieve the bearer token
3. Add the access token to your Authorization header (can use an extension like [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj)). 
4. Try to activate Yubico MFA for the user matching this access token through `auth/yubi/activate/`
5. `KeyError` should present itself.

**Expected behavior**
Either a successful response and yubico MFA activated for the user, or a 400 response with an error message. The fact that there is no 400 response and instead a KeyError blows up the endpoint I think confirms a bug

**Screenshots**
![image](https://user-images.githubusercontent.com/10172142/139947302-634ad3f5-8c8d-4bf5-afa2-276c8c5455d5.png)

**Stack Trace**
```
backend     | Internal Server Error: /auth/yubi/activate/
backend     | Traceback (most recent call last):
backend     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
backend     |     response = get_response(request)
backend     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
backend     |     response = self.process_exception_by_middleware(e, request)
backend     |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
backend     |     response = response.render()
backend     |   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 106, in render
backend     |     self.content = self.rendered_content
backend     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/response.py", line 72, in rendered_content
backend     |     ret = renderer.render(self.data, accepted_media_type, context)
backend     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/renderers.py", line 724, in render
backend     |     context = self.get_context(data, accepted_media_type, renderer_context)
backend     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/renderers.py", line 656, in get_context
backend     |     raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
backend     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
backend     |     serializer = view.get_serializer()
backend     |   File "/usr/local/lib/python3.7/site-packages/rest_framework/generics.py", line 112, in get_serializer
backend     |     return serializer_class(*args, **kwargs)
backend     |   File "/usr/local/lib/python3.7/site-packages/trench/serializers.py", line 79, in __init__
backend     |     self.get_serializer_field_mapping()[klass](
backend     | KeyError: None

```

**Desktop (please complete the following information):**
 - OS: PopOS
 - Browser Brave
 - Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)

**Additional context**
I also [cannot get Yubico working on the demo app](https://github.com/merixstudio/django-trench/issues/119)

**Comment by wmaciejewskimer** [comment]
@Frikster Does this issue still occur? Error https://github.com/merixstudio/django-trench/issues/119 is fixed and there is no error in the test application.

**Comment by wmaciejewskimer** [comment]
Closing since lack of response for 4 months.
