### ISSUE TITLE
Trying to activate, code is always Invalid or Expired. 

### ISSUE THREAD

**Issue by camelgod** [merixstudio/django-trench#123]
**Describe the bug**
Trying to activate MFA on the `/app/activate/confirm/` always give the following response:
```
{
  "code": [
    "Code invalid or expired."
  ]
}
```
Any leads or tips or tricks would be really appreciated! :)

**To Reproduce**
1. Using Insomnia or Postman, login and get token
2. Use token as bearer, make request to `127.0.0.1:8000/auth/app/activate/`
3. Get the otpauth, make QR code and scan with Authenticator app of choice
4. Try using the code from authenticator on `127.0.0.1:8000/auth/app/activate/confirm'
5. Get the error message above about code invalid or expired

**Expected behavior**
Should return the backup codes as described in the API endpoint documentation

**Screenshots**
```
{
  "code": [
    "Code invalid or expired."
  ]
}
```

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Insomnia

**Additional context**
Tried to set the timezone of Django, and timezone of my computer, but its just not happening.
Tried also to wipe the sqlite3 database, make new users, etc.

**Comment by camelgod** [comment]
Seems like the way "app" is validated is different from email. Email works fine, copying email secret over to App method also works. Could it be something with timezones? 

There is alot of timezone stuff in https://github.com/pyauth/pyotp/blob/develop/src/pyotp/totp.py#L11 but I dont understand any of it..

**Comment by camelgod** [comment]
The situation seems like the following:

Activate MFA "app", but Token Time has to be set to 1 second on the TOTP generator is the only way it works.. We expected 30.

Is there a way to force token time to 30? Or is it a bug that it´s validating only on codes generated from 1? 

Is it even possible to scan the QR-code with token time 1?  There is no way to set it in Google Authenticator to 1.

**Comment by allow-cookies** [comment]
Each MFA method has a `VALIDITY_PERIOD` property which can be set to any number of seconds per MFA method (by default it's 30`).`

For example, for `sms_twilio` MFA method you can find:

https://github.com/merixstudio/django-trench/blob/27b61479e6d494d7c2e94732c1d186247dac8dd9/trench/settings.py#L79

and by overriding this value you can set the validity period to any value of your choice.

Is this something that satisfy your needs or are you refering to something else?

**Comment by camelgod** [comment]
> Each MFA method has a `VALIDITY_PERIOD` property which can be set to any number of seconds per MFA method (by default it's `30`).
> 
> For example, for `sms_twilio` MFA method you can find:
> 
> https://github.com/merixstudio/django-trench/blob/27b61479e6d494d7c2e94732c1d186247dac8dd9/trench/settings.py#L79
> 
> and by overriding this value you can set the validity period to any value of your choice.
> 
> Is this something that satisfy your needs or are you refering to something else?

Just a disclaimer I'm not super familiar with the TOTP / pyotp libraries, but I will try my best to explain my thoughts

I tried to set the validity period while debugging this but the issue still the same. My guess is that the TOTP initialisation interval and Token Validity are two different things and should have different settings. If validity period is supposed to adjust the interval used in pyotp, its not making its way there through initialisation or other. It should be reproducible by following the steps in original post.

https://totp.danhersam.com/

This site can generate TOTP with seed and optional token period. Having the `default=1` in `create_otp.py` makes codes with "TOKEN PERIOD" = 1 in the generator work fine. But the default for things like Microsoft Authenticator is 30. I think the output of a TOTP generator (with a default interval 30) will not match up with the pytotp validate function (using interval 1) because it will have different timing. 

Thats why I propose to make the initialisation of the TOTP in create_otp.py default to 30 and make it configurable for other use cases. Email worked fine though, but I think it may not use the build_uri / provisioning_uri functions or use something different deeper into pyotp.

I didn't test the impact of this change email and other endpoints (it was late at night hehe), which is why the tests for email in the PR failed. I need to look more into it before another attempt. :)

**Comment by allow-cookies** [comment]
Ok, thank you for your explanation. I will take a deeper look into it.
