### ISSUE TITLE
Invalid code  when trying to activate MFA by `app` method

### ISSUE THREAD

**Issue by Mykhailo-Istomin** [merixstudio/django-trench#136]
**Describe the bug**
Invalid code when trying to activate MFA by `app` method
```{
    "code": [
        "Code invalid or expired."
    ]
}
````

**To Reproduce**
1. Send `POST` request to `/auth/app/activate/`
2. Scan your qr code with a mobile app
3. Send `POST` request to `/auth/app/activate/congirm` with body {"code": <CODE>}
4. See error `"code": ["Code invalid or expired."]`

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 100.0.4896.75 

**Additional context**
Issue exists only with `app` MFA method

**Comment by ajay-actuary** [comment]
I can confirm the same behavior. in Gentoo Linux I'm able to create the token but unable to validate it. TOTP codes generated in bitwarden & I confirmed the output from the pyotp totp module is the same as the token I generate. My post is as below:

`http --form POST http://127.0.0.1:8000/auth/app/activate/confirm/ 'Authorization: Bearer jwttoken' "code"="503246"`

**Comment by jhurej** [comment]
Thanks for reporting.  @Mykhailo-Istomin Not sure why did you send empty code instead of one time password from you app. Could you specify in what version of django-trench you have this issue?

**Comment by jhurej** [comment]
@ajay-actuary I checked the issue using django-trench 3.1  & bitwarden mobile app with trench set as below in settings.py
```TRENCH_AUTH{
...
"app": {
            "VERBOSE_NAME": "app",
            "VALIDITY_PERIOD": 30,
            "USES_THIRD_PARTY_CLIENT": True,
            "HANDLER": "trench.backends.application.ApplicationMessageDispatcher",
        },
 }       
```
As far I can see, there's no issue with Bitwarden if VALIDITY_PERIOD is set to proper value. 
<img width="620" alt="Screenshot 2022-10-27 at 21 20 25" src="https://user-images.githubusercontent.com/77105498/198380672-bba0f09a-a85e-45b7-87c1-026168015b96.png">
