### ISSUE TITLE
2FA cannot be deactivated starting with trench 0.3

### ISSUE THREAD

**Issue by benzkji** [merixstudio/django-trench#137]
**Describe the bug**
with pre-0.3 versions, I could disable all mfa methods. this is no more possible with trench 0.3 and upwards, is this correct?

**To Reproduce**
try to disable your last enabled mfa method.

**Expected behavior**
should be possible?

**Comment by jhurej** [comment]
@benzkji Hey, not sure if I get what you mean. I understand you  you can't disable your last mfa method but is it you primary mfa method? Do you receive `{
    "error": "Deactivation of MFA method that is set as primary is not allowed."
}`  or other type of error?

**Comment by benzkji** [comment]
I did receive that error, yes (Deactivation of MFA method that is set as primary is not allowed). Must it not be possible to disable my last mfa method, even if it is my primary one? Or is there a way to set it as "not primary"? I dont get the logic behind of it ;-)

**Comment by jhurej** [comment]
Looks like it's an issue that there's no way of disabling the last mfa method because it's primary. There should be a way of disabling all mfa. I'll fix it soon

**Comment by benzkji** [comment]
ok, thanks for the feedback. yes it should be possible to remove the last available mfa method, even if it is the primary one (it will always be, I guess ;-). Preventing the removal of the primary mfa method if there are others makes sense, otherwise.

**Comment by benzkji** [comment]
thank you, jukub!
