### ISSUE TITLE
Add active methods to /login/ response

### ISSUE THREAD

**Issue by g3rb3n** [merixstudio/django-trench#147]
**Is your feature request related to a problem? Please describe.**
Currently /login/ has a method field which gives the primary method. It would be nice if all active methods are in the response, so that a end user can choose which method to use for the second step.

**Describe the solution you'd like**
Add a methods field to the login response with all active method names.

**Describe alternatives you've considered**
Use  /mfa/user-active-methods/ , which requires a second call to the server.

**Additional context**
None

**Comment by wmaciejewskimer** [comment]
Hi @g3rb3n, As you wrote in alternatives, you can use /mfa/user-active-methods/, there is no need to always return all active methods on login. In response, there is already a primary active method
