### ISSUE TITLE
Sending of messages fails on SendGrid

### ISSUE THREAD

**Issue by g3rb3n** [merixstudio/django-trench#149]
**Describe the bug**
The SendGrid client uses json to do the API request to SendGrid. The subject field is a lazy proxy which not json serializable. This results in an 'TypeError: Object of type __proxy__ is not JSON serializable' error.

**To Reproduce**
- implement SendGrid as django email backend with django-sendgrid-v5
- call /email/activate/

**Expected behavior**
Email being send.

**Screenshots**
None

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
A simple fix is to enforce conversion of django.utils.functional.lazy.<locals>.__proxy__ to str type. Using a template for the subject would also work.

**Comment by wmaciejewskimer** [comment]
Hi @g3rb3n, Can you give us an example to reproduce this error? In the [basic example](https://github.com/sklarsa/django-sendgrid-v5#simple) of django-sendgrid-v5 subject is in string and no need for conversion. I've also tried to reproduce this issue and after installation of django-sendgrid-v5 URL /email/activate/ work well.

**Comment by allow-cookies** [comment]
Closing since lack of response for 5 months.

**Comment by g3rb3n** [comment]
@wmaciejewskimer Yes, the basic example of django-sendgrid-v5 subject is in string. The problem was that self._config.get(EMAIL_SUBJECT) in trench/backends/basic_mail.py did not return a string, but a lazy proxy. When I converted it to a string explicitly, than the mails where being send. subject=str(self._config.get(EMAIL_SUBJECT)) worked fine.
