### ISSUE TITLE
Translations for en de pl have only empty msgstr

### ISSUE THREAD

**Issue by g3rb3n** [merixstudio/django-trench#153]
**Is your feature request related to a problem? Please describe.**
Translation files for en, de and pl are available, but the translation strings are empty.

**Describe the solution you'd like**
Translations files with filled in translations.

**Describe alternatives you've considered**
Translating with translation tools.

**Additional context**
None

**Comment by wmaciejewskimer** [comment]
Hi @g3rb3n, All translation files are waiting to be translated [here](https://www.transifex.com/merixstudio/django-trench/)

**Comment by wmaciejewskimer** [comment]
Closing since lack of response for 5 months.
