### ISSUE TITLE
When creating the TOTP URL for Google Authenticator app, the time period is set to 1 and hardcoded

### ISSUE THREAD

**Issue by dhruvrajgupta** [merixstudio/django-trench#155]
When creating the TOTP URL for Google Authenticator app, the time period is set to 1 and hardcoded.
This becomes annoying when using Google Authenticator as the codes keep changing within 1 second.
The codes do work but the end user should be given enough time to view the code and enter them in our respective application.

I looked into to the lib and found that changing this particular file:
"/trench/command/create_otp.py" line 7 
and changing the interval helps to create a time period that is desired

but it would be way better if it were set according to the values set in the settings page

**Comment by allow-cookies** [comment]
The interval is no more hardcoded and uses the value from configuration. This issue has been fixed in the `0.3.1` release.
