### ISSUE TITLE
PIP doesn't install the latest version of django-trench

### ISSUE THREAD

**Issue by cloudlessdreams** [merixstudio/django-trench#159]
When installing django-trench 

`pip install django-trench`

pip only installs version 0.3.0 even when specifying the version

`pip install django-trench==0.3.1`

it shows as non-existent distribution (even tried --pre as it may have been incorrectly tagged)

<img width="1145" alt="Screenshot 2022-05-04 at 16 01 08" src="https://user-images.githubusercontent.com/12978446/166712781-fef485c1-5f46-4afa-bc25-8a177f6b7264.png">

The latest version is obviously `0.3.1`  seen here 

<img width="293" alt="Screenshot 2022-05-04 at 16 01 44" src="https://user-images.githubusercontent.com/12978446/166713191-4fd8b598-7872-4dee-9cb5-241eab0f6176.png">

and a temporary work around is to pip install from the repo itself like so..

`pip install -e git+https://github.com/merixstudio/django-trench.git#egg=django_trench`

which installs the latest distro
.... 
This issue also relates to #155 where the `VALIDITY_PERIOD` has no effect due to the interval being hardcoded but is resolved in v0.3.1 

version 0.3.1

```
class CreateOTPCommand:
    @staticmethod
    def execute(secret: str, interval: int) -> TOTP:
        return TOTP(secret, interval=interval)
       
create_otp_command = CreateOTPCommand.execute
```

version 0.3.0

```

class CreateOTPCommand:
    @staticmethod
    def execute(secret: str) -> TOTP:
        return TOTP(secret, interval=1)


create_otp_command = CreateOTPCommand.execute

```

**Comment by allow-cookies** [comment]
That's probably because we pushed the docs for `v0.3.1` too early, along with the test release to test.pypi.org but haven't deployed the `v0.3.1` release to pypi.org. It should work as expected as of now.
