### ISSUE TITLE
Reactivating the primary disabled MFAMethod introduces an inconsistent state  

### ISSUE THREAD

**Issue by andruten** [merixstudio/django-trench#169]
Hi! First of all, thank you for this awesome package!

**Describe the bug**
Reactivating the disabled primary MFAMethod should maintain `is_primary=True`. This is not working as expected because [this statement](https://github.com/merixstudio/django-trench/blob/e5deca4355311fadb3b732d86c7d545001cf421c/trench/command/activate_mfa_method.py#L29) doesn't take into account if the primary method is the affected one in the process.

**To Reproduce**
This is the full process for reproducing it.

#### Login
```
curl -X POST http://localhost:8000/auth/jwt/login/ -H  "Content-Type: application/json" -d '{"username": "admin", "password": "admin"}'
{"refresh":"...","access":"..."}
```

#### Activate app method
```
curl -X POST http://localhost:8000/auth/app/activate/ -H "Authorization: Bearer ..."
{"details":"otpauth://totp/MyApplication:admin?secret=HAA2VOHKZMJV6I6Y2JYX26OV7SMOULWO&issuer=MyApplication&period=600"}
```

#### Confirm app method
```

curl -X POST http://localhost:8000/auth/app/activate/confirm/ -H "Authorization: Bearer ..." -H  "Content-Type: application/json" -d '{"code": "231528"}'
{"backup_codes":["931780504135","028493362694","608422503394","034115886743","890942714207","867642128148","293494835872","567079811791"]}
```
<img width="831" alt="Captura de Pantalla 2022-06-13 a las 8 57 29" src="https://user-images.githubusercontent.com/5434104/173301589-808a97ff-8d7c-4f1c-89af-92c20c8cd0c7.png">

#### Deactivate app method
```
curl -X POST http://localhost:8000/auth/app/deactivate/ -H "Authorization: Bearer ..." -H  "Content-Type: application/json" -d '{"code": "818437"}'
(no content)
```
<img width="858" alt="Captura de Pantalla 2022-06-13 a las 8 58 38" src="https://user-images.githubusercontent.com/5434104/173301628-f71ac128-242f-4a55-bdd7-81907281741f.png">

#### Reactivate app method
```
curl -X POST http://localhost:8000/auth/app/activate/ -H "Authorization: Bearer ..." -H  "Content-Type: application/json"
{"details":"otpauth://totp/MyApplication:admin?secret=HAA2VOHKZMJV6I6Y2JYX26OV7SMOULWO&issuer=MyApplication"}
```

#### Reactivate app method confirm
```
curl -X POST http://localhost:8000/auth/app/activate/confirm/ -H "Authorization: Bearer ..." -H  "Content-Type: application/json" -d '{"code": "036716"}'
{"backup_codes":["684375266907","082071192573","288256663115","727551988514","106943114872","437314901576","714604541769","675806917849"]}
```
<img width="858" alt="Captura de Pantalla 2022-06-13 a las 9 01 03" src="https://user-images.githubusercontent.com/5434104/173301656-41793859-b64b-49e7-8fa5-f23272ec221a.png">

**Expected behavior**
MFAMethod instance should keep `is_primary=True` and `is_active=True` but it doesn't.

I fixed this behavior annotating the primary method instead of using `MFAUserMethodManager.primary_exists` method. 

I'll publish the fix in a PR.

**Comment by maxim25** [comment]
Is this library still active? How come this is still an open issue?

**Comment by wmaciejewskimer** [comment]
Fixed in: https://github.com/merixstudio/django-trench/pull/186
