### ISSUE TITLE
Unable to use custom user model with USERNAME_FIELD

### ISSUE THREAD

**Issue by cody-lofty** [merixstudio/django-trench#173]
Unable to activate 'app' method when using a custom user model that does not have a `username` field.

In backends/application.py, the default django user model is being imported directly via `from django.contrib.auth.models import User` instead of using `from django.contrib.auth import get_user_model`. This results in an error `"details": "'User' object has no attribute 'username'"` when generating the QR link.

There are several places where this is done correctly but serializers.py, backends/application.py, and views/base.py are using the default user model.

**Comment by gertjanvg** [comment]
We are experiencing the same problem, the PR would fix this for us.

**Comment by jhurej** [comment]
PR merged to dev, closing
