### ISSUE TITLE
Re-activating the only method previously deactivated results in is_active=1 and is_primary=0

### ISSUE THREAD

**Issue by gerolamo-ov** [merixstudio/django-trench#200]
**Describe the bug**
Re-activating the only method previously deactivated results in is_active=1 and is_primary=0

**To Reproduce**
1. Activate a single method for an user
2. Deactivate the only method for the same user
3. Activate again the method for the same user

**Expected behavior**
The activated method is the only one and so is primary

**Proposed bugfix**

change:
def primary_exists(self, user_id: Any) -> bool:
        return self.filter(user_id=user_id, is_primary=True).exists()

to;
def primary_exists(self, user_id: Any) -> bool:
        return self.filter(user_id=user_id, is_primary=True, is_active=True).exists()

**Comment by gerolamo-ov** [comment]
To be more clear, if you have only one MFA method and you follow the steps explained, you'll have is_active = True and is_primary=False and than **MFA is not enabled** for the user, this is clearly undesirable behavior and a bug

**Comment by andruten** [comment]
It has been addressed in https://github.com/merixstudio/django-trench/pull/186

**Comment by gerolamo-ov** [comment]
oh, thanks.
So we need a new release with the bugfix :)

**Comment by jchow-hedgedesk** [comment]
@gerolamo-ov any ETA on when the next release will be?

**Comment by gerolamo-ov** [comment]
@jchow-hedgedesk not from me.... I'm waiting with you...
