### ISSUE TITLE
Current develop branch needs makemigrations run to add 0005 migration

### ISSUE THREAD

**Issue by smurphles** [merixstudio/django-trench#205]
**Describe the bug**
Current develop branch is missing migration
    
**To Reproduce**
1. Run `makemigrations --check --dry-run`
2. See missing migrations

```
    - Remove constraint primary_is_active from model mfamethod
    - Create constraint primary_is_active on model mfamethod
```

**Expected behavior**
Migrations should be up to date

**Comment by nefrob** [comment]
Will be resolved with #206 if not done beforehand.
