### ISSUE TITLE
Secret length of 20 won't worth with Google Authenticator

### ISSUE THREAD

**Issue by lanthos** [merixstudio/django-trench#33]
Hello,

Trying to set this up to use Google Authenticator for MFA and the secret that is returned is 20 characters long.  The Google auth app requires 16 characters.  I'm not sure if there are requirements on any others but it might make sense to make this a variable in the settings file for the app MFA method.  I'm happy to do a PR for this if you would like.

Cheers!

**Comment by tallpol3** [comment]
Hi Jeremy,
Thanks for the hint. On what platform do you run Google Authenticator app? I've tested couple of secret keys of different length with app on Android and it accepts all keys > 16 characters. There were some known issues with that on iOS. 

But overall it's good idea to add setting for that, so go ahead with PR. We'll add it in new release.

**Comment by lanthos** [comment]
Hi Bartek,

PR submitted!  I, and most of the people at my company, are using iOS and it does have that restriction.  I've made the defaults to be 20 so it was the same as you had previously but it might be worth putting this to 16 to have broader default compatibility?  While I did update the docs, not everyone reads those. :D

**Comment by tallpol3** [comment]
Hi Jeremy,
Time to close the issue. All merged and new version released.
