### ISSUE TITLE
no attribute '_action' error when trying to verify code

### ISSUE THREAD

**Issue by benzkji** [merixstudio/django-trench#44]
I've setup django-trench together with djoser. Normal login works, across the trench endpoint (/auth/login). When activating 2FA, I can login, get the ephemeral_token, get the email/sms. But when trying to validate the code, I get the following error (submitting the correct code. with wrong code, there is an error saying "invalid code") :

    .../site-packages/trench/views/authtoken.py", line 9, in handle_user_login
        return self._action(serializer)
    AttributeError: 'AuthTokenLoginWithMFACode' object has no attribute '_action'

I have no clue where _action should be defined? I've not found it in one of the mixins, neither on the DRF APIView?

    urls.py
    url(r'^auth/', include('trench.urls')),
    url(r'^auth/', include('djoser.urls')),
    url(r'^auth/', include('djoser.urls.authtoken')),
    url(r'^auth/', include('trench.urls.djoser')),

python: 3.6.7
django: 2.1.8 / 2.2 (tried both) 
djangorestframework: 3.9.2
djoser: 1.5.1
django-trench: 0.2.1

**Comment by benzkji** [comment]
also with `djangorestframework==3.8.2`

any ideas? will dig in a bit...

**Comment by benzkji** [comment]
found it: https://github.com/sunscrapers/djoser/blob/master/djoser/views.py#L154

looks like this just cannot work, as it is developed now?

**Comment by benzkji** [comment]
found a solution. PR coming.

**Comment by tallpol3** [comment]
Awesome, thanks @benzkji 
I'll add some comments on #45, so that we can come to the best solution.

**Comment by tallpol3** [comment]
Merged, thanks again @benzkji
New release coming soon.
