### ISSUE TITLE
CodeLoginSerializer ignores VALIDITY_PERIOD setting

### ISSUE THREAD

**Issue by SaskoVitaliy** [merixstudio/django-trench#46]
CodeLoginSerializer uses only DEFAULT_VALIDITY_PERIOD so provided code fails if validity period for concrete MFA method is different than default one.

**Comment by benzkji** [comment]
also, if one copy pastes the defaults from here: https://django-trench.readthedocs.io/en/latest/settings.html#additional-settings you only have 30 seconds! ;-)

**Comment by tallpol3** [comment]
Guys, thanks for your input. Will have it investigated. 
Btw. 30 secs is a lot 😛

**Comment by allow-cookies** [comment]
Fixed in new version `0.3.0`
