### ISSUE TITLE
error when using mutliple auth backends

### ISSUE THREAD

**Issue by benzkji** [merixstudio/django-trench#49]
Using django-axes, that adds a second authentication backend, I get the following error, from this line: https://github.com/sunscrapers/djoser/blob/master/djoser/utils.py#L19

ValueError: You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.

When logging in on the "code" endpoint, ie posting the received code. I'll investigate.

- django-trench==0.2.2
- djoser==0.7

**Comment by benzkji** [comment]
uuu. could be in conjunction with my custom user model...ignore for now!

**Comment by benzkji** [comment]
has anybody used trench with multiple authentication backends enabled (django-axes is only a special case, of the same scenario...)? after the first, official/password login, that then triggers MFA, the used backend should somewhere be stored, not? Otherwise, it will not be available when the login with code is done.

**Comment by benzkji** [comment]
On the `MFAMethod` model, add a field called `used_auth_backend`. After login with user/pw, set it according to the used backend, then, when actually login in with code, provide the backend to the `login` method. 

I can stick together a PR, if it sounds reasonable? @tallpol3 what do you think?

**Comment by benzkji** [comment]
any news? any trench users implementing django-axes? also, as I understand, this is only applied when using sessions for auth...jwt and authtoken dont store the backend used to login?!?

**Comment by mhmrx** [comment]
@benzkji Can you show your settings.py file?

**Comment by vThaian** [comment]
Make sense for me to assign used backend by the user during the process. I think @benzkji you can create a PR with those changes if you want. @tallpol3 what do you think?

**Comment by Ryszyy** [comment]
I think that issue was resolved with this PR:
https://github.com/sunscrapers/djoser/pull/481

**Comment by allow-cookies** [comment]
With the new release we are not relying on `djoser` anymore. Closing.

**Comment by benzkji** [comment]
does django-trench still support using it together with djoser? at least there are still some urls.py examples with djoser....just curious...

**Comment by allow-cookies** [comment]
No, we've decided to not use `djoser` anymore as there was no further need to do so. Of course this doesn't mean that you can not use `djoser` along with `django-trench` - you still can 🙂

**Comment by benzkji** [comment]
thanks for clarifying!

**Comment by funkybob** [comment]
I've run into the same basic problem.

Django 3.2
django-trench 0.3.1

Am using custom views to log in using plain session auth, and my `_successful_authentication_response` method calls `login` from `django.contrib.auth`

However, since I have a second auth backend installed, it fails:
```
ValueError: You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.
```

This is because `authenticate` isn't called in the Step 2 code path, so the `user` instance doesn't have `backend` set on it :/

I was going to store the `user.backend` from Step 1 in the session, but I can't see anywhere I can cleanly hook int in my subclass to affect that.

**Comment by benzkji** [comment]
this should probably re-opened, it is not djoser related, but something that always occurs when using multiple auth backends, if I remember correctly? @allow-cookies

**Comment by funkybob** [comment]
Correct, this is specifically to do with having multiple auth backends.

If you try to call `login()` on a `User` instance that has not come from `authenticate()`, you will hit this issue.

https://github.com/django/django/blob/main/django/contrib/auth/__init__.py#L123

**Comment by funkybob** [comment]
I'm happy to open this as a new issue if you'd prefer.
