### ISSUE TITLE
Django 3.0 Compatibility

### ISSUE THREAD

**Issue by beittenc** [merixstudio/django-trench#64]
Django 3.0 has now been released and I've run into a minor compatibility issue.  In the SimpleJWT view, there's a reference to the django.utils.six library, which has been removed.

https://github.com/merixstudio/django-trench/blob/c0756a93f0acb8db00482087547842988b22caf3/trench/views/simplejwt.py#L1

If there's a need to maintain Python 2 compatibility, then the text_type method still exists in the six library, but it'll have to be included separately.

**Comment by vThaian** [comment]
Thank you @beittenc for added that issue. We do not support Python2 longer so we will remove that unneeded piece of code.
