### ISSUE TITLE
testapp - TypeError: Cannot read property 'is_primary' of undefined

### ISSUE THREAD

**Issue by bplociennik** [merixstudio/django-trench#68]
When we logged in and try to switch to another method let's say from e-mail auth to application auth.

![Zrzut ekranu 2019-12-5 o 07 59 27](https://user-images.githubusercontent.com/6594923/70211443-60070600-1735-11ea-936c-ef2d4efe46d8.png)

We click the proper checkbox  and we will decide to abort the changing method by uncheck field then we got the error:

![Zrzut ekranu 2019-12-5 o 08 02 35](https://user-images.githubusercontent.com/6594923/70211532-a2c8de00-1735-11ea-8d2c-d426defc8bb8.png)

**Comment by allow-cookies** [comment]
Testapp's front end is removed in the new release.
