### ISSUE TITLE
missing EMAIL_PLAIN_TEMPLATE and EMAIL_HTML_TEMPLATE breaks method activation

### ISSUE THREAD

**Issue by nicokant** [merixstudio/django-trench#73]
Hi, thanks for your fantastic work!

As the title says currently when setting `email` as TRENCH_AUTH MFA method, if no email template is specified the server returns 500 to `/email/activate/`.

I'm currently using django-trench 0.2.3

I'd suggest mentioning it inside documentation, as the error seems to be quite difficult to understand without investigating the stacktrace and the source code. Also a good idea may be providing a default for this configuration.

I'd like to help, so let me know if I can submit a PR to fix this.
Thanks again!

**Comment by allow-cookies** [comment]
@nicokant could you please verify whether this issue still emerges in the new `0.3.0` version?
