### ISSUE TITLE
Request Resend

### ISSUE THREAD

**Issue by cobyrne09** [merixstudio/django-trench#88]
Hey there, while you have the 'request resend' functionality in your demo project, it doesn't seem as though there is an actual endpoint for this? I just want to make sure before I try to build this myself!

Assuming I need to build this, I suspect you would just POST the ephemeral token and the method, and a new code would be sent, and you would keep the same ephemeral token. Does that sound OK to your team?

**Comment by allow-cookies** [comment]
Hey! Sorry for late response. `django-trench` provides the `/code/request` URL that can be used for this purpose. The implementation of this view can be found in `views/base.py::MFAMethodRequestCodeView`

**Comment by cody-lofty** [comment]
`/code/request` is protected by `IsAuthenticated`, so there's no way to use this to resend an email code at login, for example
