### ISSUE TITLE
Error: “Secrets must be at least 160 bits.”

### ISSUE THREAD

**Issue by be-studio** [merixstudio/django-trench#89]
When trying to post to the `/authenticate` endpoint I get a 500 server error and the error message reads: “Secrets must be at least 160 bits”. This only occurs in production; it works with no issues in development. I really need to get this working as a deadline is upon me. Can you please help?

P.S. Using a Docker microservices setup. There are near identical settings between dev and prod, and the Python package versions between the environments match. There are valid secret key for Django and signing key for django-rest-framework-simplejwt.

**Comment by reddytocode** [comment]
In settings add
`TRENCH_AUTH = {
    'SECRET_KEY_LENGTH': 32, 
    ...
  }
  `
maybe can help, the error is thrown when this secret is less than 32
I guess is in the pyotp library

**Comment by be-studio** [comment]
Thank you @reddytocode . That solves the problem.
